module.exports = {
  config: {
    updateChannel: 'canary',
    fontSize: 16,
    fontFamily: 'Operator Mono Lig',
    fontWeight: 'normal',
    fontWeightBold: 'bold',
    lineHeight: 1,
    letterSpacing: 0,
    cursorColor: 'rgba(248,28,229,0.8)',
    cursorAccentColor: '#000',
    cursorShape: 'BLOCK',
    cursorBlink: true,
    foregroundColor: '#fff',
    backgroundColor: '#000',
    selectionColor: 'rgba(248,28,229,0.3)',
    borderColor: '#333',
    padding: '12px 14px',
    colors: {
      black: '#000000',
      red: '#C51E14',
      green: '#1DC121',
      yellow: '#C7C329',
      blue: '#0A2FC4',
      magenta: '#C839C5',
      cyan: '#20C5C6',
      white: '#C7C7C7',
      lightBlack: '#686868',
      lightRed: '#FD6F6B',
      lightGreen: '#67F86F',
      lightYellow: '#FFFA72',
      lightBlue: '#6A76FB',
      lightMagenta: '#FD7CFC',
      lightCyan: '#68FDFE',
      lightWhite: '#FFFFFF',
    },
    shell: 'C:\\Windows\\System32\\bash.exe',
    shellArgs: ['--login', '-c', 'zsh'],
    bell: false,
    copyOnSelect: true,
    defaultSSHApp: true,
    macOptionSelectionMode: 'vertical',
    webGLRenderer: true,
    hypercwd: {
      initialWorkingDirectory: '~/',
    },
  },
  plugins: [
    "hyper-material-theme",
    "hypercwd",
    "hyper-search"
  ],
};
